name: Deploy Backend + CDK

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Deploy
        working-directory: ./cdk/aws-cdk
        run: |
          npm ci
          npm run build
          npx cdk deploy --require-approval never

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
            sudo yum install nodejs git -y

            cd ~/todo-task-application || git clone https://github.com/Harathibupuri/todo-task-application.git
            cd todo-task-application

            git pull origin master
            echo "${{ secrets.ENV_FILE }}" > .env
            npm install
            npm run build

            pkill node || true
            nohup npm start > app.log 2>&1 &